### ISSUE TITLE
A3 - Implemente o BFS

### ISSUE THREAD

**Issue by prosperor** [FabioFernandesCosta/HanoiTowerCommandLine#12]
Crie uma implementação para o algoritmo de busca cega BFS

**Comment by FabioFernandesCosta** [comment]
implementado no commit [d15fa0818e42fde8d891ca051ace17b4ed9b3556](https://github.com/FabioFernandesCosta/HanoiTowerCommandLine/commit/d15fa0818e42fde8d891ca051ace17b4ed9b3556)
