### ISSUE TITLE
A4 - Implementar uma interface inicial

### ISSUE THREAD

**Issue by prosperor** [FabioFernandesCosta/HanoiTowerCommandLine#14]
Implemente um seletor de jogador no início de seu jogo, que permite escolher qual dos agentes jogará a partida a começar.

**Comment by FabioFernandesCosta** [comment]
Uso de BFS adicionado como opção no commit [d15fa0818e42fde8d891ca051ace17b4ed9b3556](https://github.com/FabioFernandesCosta/HanoiTowerCommandLine/commit/d15fa0818e42fde8d891ca051ace17b4ed9b3556)
